name: flutter_application_1
description: A new Flutter project.

# Dependências do Flutter
dependencies:
  flutter:
    sdk: flutter

  # Dependência para a fonte personalizada (substitua com a fonte e o caminho corretos)
  google_fonts: ^6.1.0

  # Dependência para as fontes Material Icons e Cupertino Icons
  cupertino_icons: ^1.0.2

# Configuração do Flutter
flutter:
  uses-material-design: true

# Definição da fonte personalizada
fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 700

  # Definição de fontes Material Icons e Cupertino Icons
  - family: MaterialIcons
    fonts:
      - asset: packages/cupertino_icons/fonts/MaterialIcons-Regular.ttf
  - family: CupertinoIcons
    fonts:
      - asset: packages/cupertino_icons/fonts/CupertinoIcons-Regular.ttf

environment:
  sdk: '^3.1.0'